# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: YmFhOTY3ZWE1NjZkNDA1ODgzZjc4OWQxN2IyZTUzY2YyYjE4ODZlZTJmYjUyY2RkNWFlOGRlNmE0ZDFhMTE4Zjg1ZTAzOTFjNzMxMjA0YjA1NGUxNDhlYmQ3MWI0YWMyOWY4YmM5M2Q2MmQwMjYxODY1OTdiM2JhYWQ1MDkyMjI=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
