# DB template.
#
# This defines all the configurable parameters and other objects that are needed to run the MariaDB service. This template can even be
# saved in OpenShift namespace as well so that have the flexibility to do any project specific customizations. Pls note wherever
# displayName says *** PLEASE DO NOT CHANGE THIS ***, don't touch that as those parameters will be referenced in other places.
#
apiVersion: v1
kind: Template
metadata:
  name: gateway-mariadb-template
  namespace: default
  annotations:
    description: This template defines objects that are required to spin up a mariadb pod
    tags: db, gateway-mariadb  ,ephemeral
    openshift.io/display-name: gateway-mariadb-template
    openshift.io/long-description: >-
      This template provides objects that are required to spin up a mariadb pod. 
      The database is not stored on persistent storage, so any restart of the service will result in all data being lost.
    openshift.io/provider-display-name: JHipster-OpenShift
labels:
  app: gateway-mariadb
  createdBy: JHipster-Team
parameters:
  - name: APPLICATION_NAME
    value: gateway-mariadb
    description: Name of the application
    required: true
    displayName: Application Name
  - name: SECRET_REF
    value: gateway-ds-secret-ref
    description: Name of the secret reference
    required: true
    displayName: "*** PLEASE DO NOT CHANGE THIS ***"
  - name: MYSQL_USER
    displayName: MariaDB Connection Username
    description: Username for MariaDB user that will be used for accessing the database.
    generate: expression
    from: user[A-Z0-9]{3}
    required: true
  - name: MYSQL_PASSWORD
    displayName: MariaDB Connection Password
    description: Password for the MariaDB connection user.
    generate: expression
    from: "[a-zA-Z0-9]{16}"
    required: true
  - name: MYSQL_ROOT_PASSWORD
    displayName: MariaDB root user Password
    description: Password for the MariaDB root user.
    generate: expression
    from: "[a-zA-Z0-9]{16}"
    required: true
  - name: DATABASE_NAME
    value: gateway
    displayName: MariaDB DB Name
    description: Name of the MariaDB database accessed.
    required: true
  - name: VOLUME_CAPACITY
    displayName: Volume Capacity
    description: Volume space available for data, e.g. 512Mi, 2Gi.
    value: 1Gi
    required: true
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: ${SECRET_REF}
    stringData:
      database-user: "${MYSQL_USER}"
      database-password: "${MYSQL_PASSWORD}"
      database-root-password: "${MYSQL_ROOT_PASSWORD}"
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: ${APPLICATION_NAME}
      labels:
        app: ${APPLICATION_NAME}
    spec:
      # This is to define the deployment strategy (either be Rolling or Recreate)
      #     strategy:
      #       type: Rolling
      #       rollingParams:
      #         updatePeriodSeconds: 1
      #         intervalSeconds: 1
      #         timeoutSeconds: 600
      #         maxUnavailable: 25%
      #         maxSurge: 25%
      #       resources:
      triggers:
        - type: ConfigChange
      replicas: 1
      selector:
        app: ${APPLICATION_NAME}
      template:
        metadata:
          labels:
            app: ${APPLICATION_NAME}
        spec:
          volumes:
            - name: ${APPLICATION_NAME}-data
              emptyDir: {}
          containers:
            - name: ${APPLICATION_NAME}
              image: mariadb:10.5.9
              env:
                #            - name: MYSQL_USER
                #              value: root
                #            - name: MYSQL_ALLOW_EMPTY_PASSWORD
                #              value: 'yes'
                - name: MYSQL_DATABASE
                  value: ${DATABASE_NAME}
                - name: MYSQL_USER
                  valueFrom:
                    secretKeyRef:
                      name: ${SECRET_REF}
                      key: database-user
                - name: MYSQL_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: ${SECRET_REF}
                      key: database-password
                - name: MYSQL_ROOT_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: ${SECRET_REF}
                      key: database-root-password
              #        command:
              #        - mysqld
              #        - --lower_case_table_names=1
              #        - --skip-ssl
              #        - --character_set_server=utf8mb4
              #        - --explicit_defaults_for_timestamp
              ports:
                - containerPort: 3306
                  protocol: TCP
              readinessProbe:
                timeoutSeconds: 1
                initialDelaySeconds: 5
                exec:
                  command:
                    - "/bin/sh"
                    - "-i"
                    - "-c"
                    - MYSQL_PWD="$MYSQL_PASSWORD" mysql -h 127.0.0.1 -u $MYSQL_USER -D $MYSQL_DATABASE
                      -e 'SELECT 1'
              livenessProbe:
                timeoutSeconds: 1
                initialDelaySeconds: 30
                tcpSocket:
                  port: 3306
              volumeMounts:
                - name: ${APPLICATION_NAME}-data
                  mountPath: /var/lib/mysql
              resources:
              imagePullPolicy: IfNotPresent
          restartPolicy: Always
          terminationGracePeriodSeconds: 30
  - apiVersion: v1
    kind: Service
    metadata:
      name: ${APPLICATION_NAME}
      labels:
        app: ${APPLICATION_NAME}
    spec:
      ports:
        - name: mariadb-bc
          protocol: TCP
          port: 3306
          targetPort: 3306
        - name: mariadb
          protocol: TCP
          port: 80
          targetPort: 3306
      selector:
        app: ${APPLICATION_NAME}
